/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/import_njsbcl_grounds_xlsx.py — do not edit.
 * Source sheet: Grounds in 2026 NJSBCL Final Schedule.xlsx
 */

export type NjsbclGroundRow = {
  teamsSharing: string;
  town: string;
};

export const NJSBCL_GROUND_ROWS: NjsbclGroundRow[] = [
  {
    "teamsSharing": "NJ Yorkers, Jersey Titans, Warriors, Jersey Superstars",
    "town": "Avenel"
  },
  {
    "teamsSharing": "Crimson Hawks, Jersey Vikings, Edison Super Kings",
    "town": "Branchburg"
  },
  {
    "teamsSharing": "Royal Strikers, Jersey City Dominators, Cricket Lovers, Bayonne CC",
    "town": "Bayonne"
  },
  {
    "teamsSharing": "Super Challengers, NJ Titans, Newport Narcos, RRR",
    "town": "Bayonne"
  },
  {
    "teamsSharing": "VRK Gladiators, Windsor Warriors, Mag11",
    "town": "Howell"
  },
  {
    "teamsSharing": "Karma Weekenders",
    "town": "Milltown"
  },
  {
    "teamsSharing": "Montgomery Knights CC (Sat), MKCC Weekenders (Sat)",
    "town": "Belle Mead"
  },
  {
    "teamsSharing": "Saffron Sapphire, Tridents XI",
    "town": "New Brunswick"
  },
  {
    "teamsSharing": "Orion Stars, EM Sports Club, Goldfinch CC, Jersey Knights CC",
    "town": "Plainfield"
  },
  {
    "teamsSharing": "Jersey Panthers, Jersey Lions, Giant Slayers, Bisons XI",
    "town": "Bridgewater"
  },
  {
    "teamsSharing": "Gymkhana CC, Lion King, Falcons, Cricket Warriors",
    "town": "Somerset"
  },
  {
    "teamsSharing": "Maywood Indians, Supernovas, Bergen Warriors, FDU Giants",
    "town": "South Hackensack"
  },
  {
    "teamsSharing": "Kallol of NJ (Sun), Edison Rebelz (Sun), Gujarat United XI (Sat)",
    "town": "Somerset"
  },
  {
    "teamsSharing": "Samudhra Gladiators (Sat), NJ Braves (Sat), WCC (Sun)",
    "town": "Monroe Township"
  },
  {
    "teamsSharing": "Monroe Mavericks, Firehawks",
    "town": "Howell"
  },
  {
    "teamsSharing": "Cedar Falcons (Sat), RHG (Sat)",
    "town": "Edison"
  },
  {
    "teamsSharing": "Straight Drive CC, Edison Warriors, Ridge CC, Telugu Titans - Weekenders",
    "town": "Manville"
  },
  {
    "teamsSharing": "Bengal Express (Sun), Brown Munde (Sun)",
    "town": "Paterson"
  },
  {
    "teamsSharing": "22 Yards, NJ Stars CC",
    "town": "Parlin"
  },
  {
    "teamsSharing": "Perryville Panthers",
    "town": "Pittstown"
  },
  {
    "teamsSharing": "Patriots CC, JC Warriors, EB Strikers, Raptors",
    "town": "Parlin"
  },
  {
    "teamsSharing": "Gryffindors, Sreeshti Aggies, Top Guns",
    "town": "Hillsborough"
  },
  {
    "teamsSharing": "Kranti XI (Sat), Xoriant-RHG11 (Sat)",
    "town": "Parlin"
  },
  {
    "teamsSharing": "NJ Tigers, Renegades, Team Highlanders, adroIT CC",
    "town": "Piscataway"
  },
  {
    "teamsSharing": "Juggernaut, Invincible CC, Chargerz, Blasters",
    "town": "Piscataway"
  },
  {
    "teamsSharing": "Punjab XI, NJ Marvels, Edison Kings, 11Spartans",
    "town": "Union"
  },
  {
    "teamsSharing": "Maha CC, Iselin Warriors, Kennedy Kings, Jersey Boys",
    "town": "Iselin"
  },
  {
    "teamsSharing": "Mystery Squad (Sun)",
    "town": "Piscataway"
  },
  {
    "teamsSharing": "Knoll CC, Express Rangers, Parsippany Super Kings",
    "town": "Parsippany"
  },
  {
    "teamsSharing": "Hudson Hurricane Sultans (Sat), Secaucus Punters (Sun)",
    "town": "Secaucus"
  },
  {
    "teamsSharing": "Secaucus Fighters (Sat), Bergen Boys (Sun)",
    "town": "Secaucus"
  },
  {
    "teamsSharing": "Newport CC (Sun), Storm Riders (Sun)",
    "town": "Jersey City"
  },
  {
    "teamsSharing": "Youth For Sewa (Sat), Manhattan Tigers (Sat)",
    "town": "Jersey City"
  },
  {
    "teamsSharing": "Manalapan CC (Sun), MCC Weekenders (Sun)",
    "town": "Manalapan"
  },
  {
    "teamsSharing": "Marlboro CC (Sun)",
    "town": "Marlboro"
  },
  {
    "teamsSharing": "11 Hunters",
    "town": "West Windsor"
  },
  {
    "teamsSharing": "Piscataway Warriors (Sat)",
    "town": "Staten Island"
  },
  {
    "teamsSharing": "Garden State Tigers, Jersey Tigers, NJ Warriors, Jersey Indians",
    "town": "Edison"
  },
  {
    "teamsSharing": "CCE Warriors, Plainsboro Knights, NJKnights, Incredibulls",
    "town": "Belle Mead"
  },
  {
    "teamsSharing": "Somerset CC, Galli CC, Bloodline, NJ Smashers",
    "town": "Somerset"
  },
  {
    "teamsSharing": "Pway Lions, Pway Cubs, Piscataway Avengers, Piscataway Mavericks",
    "town": "Piscataway"
  },
  {
    "teamsSharing": "Renaissance Kings, Sunrisers CC, Vikings CC",
    "town": "North Brunswick"
  },
  {
    "teamsSharing": "Toms River XI",
    "town": "Toms River"
  },
  {
    "teamsSharing": "Super Kings (Sun), Jersey Colts (Sun)",
    "town": "Parsippany"
  },
  {
    "teamsSharing": "F5, Hudson Hurricanes, The Knights, Gujarat Titans",
    "town": "Leonia"
  },
  {
    "teamsSharing": "Newport Nukes (Sun), Power Hitters (Sun)",
    "town": "Leonia"
  },
  {
    "teamsSharing": "Bethak Titans, Lincoln XI, Troy Titans, Champions",
    "town": "South River"
  },
  {
    "teamsSharing": "Monroe United (Sun), Panthers (Sun)",
    "town": "Old Bridge"
  },
  {
    "teamsSharing": "Blue Leaf SC (Sun)",
    "town": "Somerset"
  },
  {
    "teamsSharing": "Smashers XI, Plainsboro Super Kings, Trident CC, Giants",
    "town": "Plainsboro"
  },
  {
    "teamsSharing": "Plainsboro Hawks, Plainsboro Hunters",
    "town": "Plainsboro"
  },
  {
    "teamsSharing": "PCC, Mercer Challengers, Plainsboro Panthers, Plainsboro Eagles",
    "town": "Plainsboro"
  },
  {
    "teamsSharing": "Jetha 11. Samp XI",
    "town": "Levittown"
  },
  {
    "teamsSharing": "GCC, PCA Jr., NJ Boxers, Shreeji XI",
    "town": "Piscataway"
  },
  {
    "teamsSharing": "Phoenix Flyers",
    "town": "North Brunswick"
  },
  {
    "teamsSharing": "The Elites",
    "town": "Princeton"
  },
  {
    "teamsSharing": "Robbinsville CC",
    "town": "Robbinsville"
  },
  {
    "teamsSharing": "Thunder Strikers CC, Thunder Strikers Weekenders, Robbinsville Jaguars",
    "town": "Robbinsville"
  },
  {
    "teamsSharing": "Woodlot Boyz, Jersey Aces, Namo XI, SB Vikings CC",
    "town": "South Brunswick"
  },
  {
    "teamsSharing": "Blue Aces CC, Princeton Walk CC, Veerans, Desi Warriors",
    "town": "South Brunswick"
  },
  {
    "teamsSharing": "Jersey Sloggers (Sun), Morris Indians (Sun)",
    "town": "Budd Lake"
  },
  {
    "teamsSharing": "Isotopes, United Falcons, Parsippany Sports Cricket XI, Parsippany Phoenix XI",
    "town": "Parsippany"
  },
  {
    "teamsSharing": "Garden State 11, Edison Riders, Waterfront Warriors",
    "town": "Branchburg"
  },
  {
    "teamsSharing": "Starz CC, Gilli, Friends XI, 107ers, SB Vikings Challengers",
    "town": "South Brunswick"
  },
  {
    "teamsSharing": "Maples SC (Sat), Karma XI (Sat), Jersey Spartans (Sun)",
    "town": "Edison"
  },
  {
    "teamsSharing": "Edison Hawks CC (Sun), Tough Boys (Sun)",
    "town": "Edison"
  },
  {
    "teamsSharing": "Blue Warriors (Sun), Jersey Stallions (Sun), Monroe Giants Club (Sat)",
    "town": "Monroe Township"
  },
  {
    "teamsSharing": "Sreeshti (Sat), Sreeshti Weekenders (Sat)",
    "town": "Hillsborough"
  },
  {
    "teamsSharing": "PMCC, Aryans, Kinnelon Colts, Yuva",
    "town": "Lake Hiawatha"
  },
  {
    "teamsSharing": "Rowdy Rebels, JC Mavericks, Sinclair Lions, SCC XI",
    "town": "Roselle"
  },
  {
    "teamsSharing": "Staten Island Strikers",
    "town": "Bloomfield"
  },
  {
    "teamsSharing": "Sparta XI (Sun)",
    "town": "Sparta"
  },
  {
    "teamsSharing": "NJ Champs (Sun)",
    "town": "Edison"
  }
];
