/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/scrape_njsbcl_grounds.py — do not edit.
 * Source: https://www.njsbcl.com/NJSBCL/viewTeams.do?league=59&year=2026&clubId=2690
 * Generated at: 2026-04-15T00:16:16Z
 */

export type TeamHomeGroundEntry = {
  team: string;
  groundName: string;
  address: string;
};

export const TEAM_HOME_GROUND_ENTRIES: TeamHomeGroundEntry[] = [
  {
    "team": "22 Yards",
    "groundName": "Eisenhower 2",
    "address": "601 Ernston Road, Parlin, NJ"
  },
  {
    "team": "CCE Warriors",
    "groundName": "Veterans Park - Spray Ground",
    "address": "61 Avenue K, Monroe Twp, NJ"
  },
  {
    "team": "Gilli",
    "groundName": "Rowland Large",
    "address": "70 Rowland Road, Cranbury, NJ"
  },
  {
    "team": "Gujarat Titans",
    "groundName": "Overpeck County Park",
    "address": "Fort Lee Road, Leonia, NJ 07605"
  },
  {
    "team": "Kinnelon Colts",
    "groundName": "Volunteer Park Parsippany",
    "address": "2 Seminole Ave, Lake Hiawatha, NJ 07034"
  },
  {
    "team": "Lion King",
    "groundName": "Colonial Park",
    "address": "Colonial Drive, Somerset, NJ"
  },
  {
    "team": "Marlboro CC",
    "groundName": "Marlboro Recreational Center Baseball Field",
    "address": "Lotta Burke Way, Marlboro Township, NJ 07746"
  },
  {
    "team": "Namo XI",
    "groundName": "Rowland Large",
    "address": "70 Rowland Road, Cranbury, NJ"
  },
  {
    "team": "Nj Yorkers",
    "groundName": "Avenel Middle School",
    "address": "85 Woodbine Ave, Avenel, NJ"
  },
  {
    "team": "Parsippany Sports Cricket XI",
    "groundName": "Volunteer Park Parsippany",
    "address": "2 Seminole Ave, Lake Hiawatha, NJ 07034"
  },
  {
    "team": "Renegades",
    "groundName": "Johnson Park 1",
    "address": "River Road, Piscataway, NJ"
  },
  {
    "team": "Robbinsville CC",
    "groundName": "Robbinsville Twp Cricket Ground",
    "address": "Breshnahan Rd, Robbinsville, NJ 08691"
  },
  {
    "team": "Secaucus Punters",
    "groundName": "Laurel Hill Park",
    "address": "New County Ave, Secaucus, NJ 07094"
  },
  {
    "team": "Somerset CC",
    "groundName": "Naaman Williams Park",
    "address": "42 Matilda Ave, Somerset, NJ 08873"
  },
  {
    "team": "Sreeshti Aggies",
    "groundName": "Hillsborough Loews",
    "address": "315 US-206 Suite 600, Hillsborough, NJ 08844"
  },
  {
    "team": "107ers",
    "groundName": "Rowland Large",
    "address": "70 Rowland Road, Cranbury, NJ"
  },
  {
    "team": "Bergen Warriors",
    "groundName": "Columbus Park",
    "address": "South Hackensack, NJ"
  },
  {
    "team": "BISONS XI",
    "groundName": "Chimney Rock Park",
    "address": "744 Chimney Rock Rd, Martinsville, NJ 08807"
  },
  {
    "team": "Galli CC",
    "groundName": "Naaman Williams Park",
    "address": "42 Matilda Ave, Somerset, NJ 08873"
  },
  {
    "team": "Giants",
    "groundName": "Plainsboro Community Park",
    "address": "Woodland Drive, Plainsboro, NJ"
  },
  {
    "team": "Jersey Lions",
    "groundName": "Chimney Rock Park",
    "address": "744 Chimney Rock Rd, Martinsville, NJ 08807"
  },
  {
    "team": "Jersey Vikings",
    "groundName": "Shakti Strikers Park",
    "address": "724 Chester Ave, Branchburg NJ 08853"
  },
  {
    "team": "Kennedy Kings",
    "groundName": "Kennedy Park",
    "address": "150 Goodrich Street, Iselin, NJ 08830"
  },
  {
    "team": "Newport Nukes",
    "groundName": "Overpeck County Park",
    "address": "Fort Lee Road, Leonia, NJ 07605"
  },
  {
    "team": "PCC",
    "groundName": "Plainsboro Turf Pitch",
    "address": "Woodland Drive, Plainsboro, NJ"
  },
  {
    "team": "Starz CC",
    "groundName": "Rowland Large",
    "address": "70 Rowland Road, Cranbury, NJ"
  },
  {
    "team": "Tough Boys",
    "groundName": "Thomas Jefferson Middle School Pitch 2",
    "address": "450 Division Street, Edison, NJ 08817"
  },
  {
    "team": "Yuva",
    "groundName": "Volunteer Park Parsippany",
    "address": "2 Seminole Ave, Lake Hiawatha, NJ 07034"
  },
  {
    "team": "Blue Warriors",
    "groundName": "Veterans Park - Spray Ground",
    "address": "61 Avenue K, Monroe Twp, NJ"
  },
  {
    "team": "Chargerz",
    "groundName": "Johnson Park 2",
    "address": "River Road, Piscataway, NJ"
  },
  {
    "team": "Crimson Hawks",
    "groundName": "Shakti Strikers Park",
    "address": "724 Chester Ave, Branchburg NJ 08853"
  },
  {
    "team": "Gymkhana CC",
    "groundName": "Colonial Park",
    "address": "Colonial Drive, Somerset, NJ"
  },
  {
    "team": "Jersey Colts",
    "groundName": "Old Troy Park",
    "address": "Parsippany, NJ"
  },
  {
    "team": "Jersey Panthers",
    "groundName": "Chimney Rock Park",
    "address": "744 Chimney Rock Rd, Martinsville, NJ 08807"
  },
  {
    "team": "Jersey Spartans",
    "groundName": "Thomas Jefferson Middle School Pitch 1",
    "address": "450 Division Street, Edison, NJ 08817"
  },
  {
    "team": "Jersey Stallions",
    "groundName": "Veterans Park - Spray Ground",
    "address": "61 Avenue K, Monroe Twp, NJ"
  },
  {
    "team": "NJ Smashers",
    "groundName": "Naaman Williams Park",
    "address": "42 Matilda Ave, Somerset, NJ 08873"
  },
  {
    "team": "Piscataway Mavericks",
    "groundName": "Normandy Pitch 1",
    "address": "99 Normandy Drive, Piscataway, NJ"
  },
  {
    "team": "Renaissance Kings",
    "groundName": "North Brunswick Comm Park",
    "address": "2053 U.S. 130 South, North Brunswick, NJ 08902"
  },
  {
    "team": "Thunder Strikers Cricket Club",
    "groundName": "Robbinsville Twp Cricket Ground",
    "address": "Breshnahan Rd, Robbinsville, NJ 08691"
  },
  {
    "team": "Adroit CC",
    "groundName": "Johnson Park 2",
    "address": "River Road, Piscataway, NJ"
  },
  {
    "team": "Bergen Boys",
    "groundName": "Laurel Hill Park",
    "address": "New County Ave, Secaucus, NJ 07094"
  },
  {
    "team": "Edison Hawks CC",
    "groundName": "Thomas Jefferson Middle School Pitch 2",
    "address": "450 Division Street, Edison, NJ 08817"
  },
  {
    "team": "Friends XI",
    "groundName": "Rowland Large",
    "address": "70 Rowland Road, Cranbury, NJ"
  },
  {
    "team": "Maywood Indians",
    "groundName": "Columbus Park",
    "address": "South Hackensack, NJ"
  },
  {
    "team": "Nj Champs",
    "groundName": "Woodrow Wilson Middle School",
    "address": "50 Woodrow Wilson Drive, Edison, NJ 08820"
  },
  {
    "team": "Orion Stars",
    "groundName": "Cedarbrook Park",
    "address": "Randolph Road, Plainfield, NJ"
  },
  {
    "team": "Panthers",
    "groundName": "Cedarbrook Park",
    "address": "Randolph Road, Plainfield, NJ"
  },
  {
    "team": "Plainsboro Super Kings",
    "groundName": "Plainsboro Community Park",
    "address": "Woodland Drive, Plainsboro, NJ"
  },
  {
    "team": "Royal Strikers",
    "groundName": "Lincoln Park Center Pitch",
    "address": "Jersey City, NJ 07306"
  },
  {
    "team": "Smashers XI",
    "groundName": "Plainsboro Community Park",
    "address": "Woodland Drive, Plainsboro, NJ"
  },
  {
    "team": "Super Kings",
    "groundName": "Old Troy Park",
    "address": "Parsippany, NJ"
  },
  {
    "team": "Supernovas",
    "groundName": "Columbus Park",
    "address": "South Hackensack, NJ"
  },
  {
    "team": "The Elites",
    "groundName": "Schalks Meadow Park",
    "address": "Parker Road, Plainsboro, NJ 08536"
  },
  {
    "team": "The Knights",
    "groundName": "Overpeck County Park",
    "address": "Fort Lee Road, Leonia, NJ 07605"
  },
  {
    "team": "Toms River XI",
    "groundName": "North Dover Elementary",
    "address": "1759 New Hampshire Ave, Toms River, NJ 08755"
  }
];
