#!/usr/bin/env python3
"""Read Grounds sheet from 2026 NJSBCL Final Schedule.xlsx → njsbcl-grounds.generated.ts"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("Install openpyxl: pip3 install openpyxl", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "lib" / "njsbcl-grounds.generated.ts"

DEFAULT_XLSX = Path.home() / "Downloads" / "2026 NJSBCL Final Schedule.xlsx"


def tokenize_sharing(cell: str) -> list[str]:
    if not cell or not str(cell).strip():
        return []
    s = str(cell).strip()
    # "Jetha 11. Samp XI" uses a period separator
    parts = re.split(r",\s*|\.\s+", s)
    out: list[str] = []
    for p in parts:
        t = re.sub(r"\s*\([^)]*\)\s*$", "", p.strip()).strip()
        if t:
            out.append(t)
    return out


def main() -> None:
    xlsx = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_XLSX
    if not xlsx.is_file():
        print(f"Missing xlsx: {xlsx}", file=sys.stderr)
        sys.exit(1)

    wb = openpyxl.load_workbook(xlsx, read_only=True, data_only=True)
    if "Grounds" not in wb.sheetnames:
        print("No 'Grounds' sheet", wb.sheetnames, file=sys.stderr)
        sys.exit(1)
    ws = wb["Grounds"]
    rows_in = [r for r in ws.iter_rows(values_only=True)]
    wb.close()

    data_rows: list[tuple[str, str]] = []
    for i, row in enumerate(rows_in):
        if i == 0:
            continue
        a, b = (row[0] if len(row) > 0 else None), (row[1] if len(row) > 1 else None)
        if a is None and b is None:
            continue
        sharing = str(a).strip() if a is not None else ""
        town = str(b).strip() if b is not None else ""
        if not sharing and not town:
            continue
        data_rows.append((sharing, town))

    entries = [{"teamsSharing": s, "town": t} for s, t in data_rows]

    def norm(x: str) -> str:
        return re.sub(r"\s+", " ", x.lower().strip())

    seen: dict[str, str] = {}
    for s, t in data_rows:
        for tok in tokenize_sharing(s):
            k = norm(tok)
            if k in seen and seen[k] != f"{s} @ {t}":
                print(f"warn: duplicate token '{tok}' → {seen[k]} vs {s} @ {t}", file=sys.stderr)
            seen[k] = f"{s} @ {t}"

    ts = f"""/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/import_njsbcl_grounds_xlsx.py — do not edit.
 * Source sheet: Grounds in {xlsx.name}
 */

export type NjsbclGroundRow = {{
  teamsSharing: string;
  town: string;
}};

export const NJSBCL_GROUND_ROWS: NjsbclGroundRow[] = {json.dumps(entries, indent=2)};
"""
    OUT.write_text(ts, encoding="utf-8")
    print(f"Wrote {len(entries)} rows → {OUT}")


if __name__ == "__main__":
    main()
