#!/usr/bin/env python3
"""Generate src/lib/team-home-grounds.generated.ts from NJSBCL team + ground pages."""
from __future__ import annotations

import json
import re
import ssl
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "lib" / "team-home-grounds.generated.ts"

TEAMS_URL = (
    "https://www.njsbcl.com/NJSBCL/viewTeams.do?league=59&year=2026&clubId=2690"
)


def fetch(url: str) -> str:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Mozilla/5.0 (compatible; GS11-scraper/1.0)"},
    )
    with urllib.request.urlopen(req, context=ctx, timeout=45) as r:
        return r.read().decode("utf-8", errors="replace")


def decode_html(s: str) -> str:
    s = (
        s.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", '"')
        .replace("&#39;", "'")
        .replace("&nbsp;", " ")
    )
    return s.strip()


def parse_team_rows(html: str) -> list[tuple[str, str | None, str | None]]:
    # Main table rows contain nested <tr>; split on each top-level row id.
    starts = [m.start() for m in re.finditer(r'<tr id="row\d+">', html)]
    blocks: list[str] = []
    for i, start in enumerate(starts):
        end = starts[i + 1] if i + 1 < len(starts) else len(html)
        blocks.append(html[start:end])

    out: list[tuple[str, str | None, str | None]] = []
    for block in blocks:
        tm = re.search(r'viewTeam\.do\?[^"]*">([^<]+)</a>', block)
        if not tm:
            continue
        team = decode_html(tm.group(1))
        gm = re.search(
            r'viewGround\.do\?groundId=(\d+)[^"]*">([^<]+)</a>',
            block,
        )
        if not gm:
            out.append((team, None, None))
            continue
        out.append((team, gm.group(1), decode_html(gm.group(2))))
    return out


def parse_ground_address(html: str) -> str:
    loc = re.search(
        r'<div class="ground-det"><h4>Location[\s\S]*?</h4>'
        r'<span class="ground-smalldet">([^<]+)</span></div>',
        html,
    )
    if loc:
        return decode_html(loc.group(1))
    form = re.search(
        r"<h5>Address:\s*</h5>[\s\S]*?<div class=\"form-in\"[^>]*>\s*([^<]+)",
        html,
    )
    if form:
        t = re.sub(r"<br\s*/?>", " ", form.group(1), flags=re.I)
        return decode_html(t)
    return ""


def main() -> None:
    print("Fetching team list…", flush=True)
    teams_html = fetch(TEAMS_URL)
    parsed = parse_team_rows(teams_html)
    ids = sorted({g for _, g, _ in parsed if g})
    print(f"Teams: {len(parsed)}, unique grounds: {len(ids)}", flush=True)

    id_to_addr: dict[str, str] = {}
    for i, gid in enumerate(ids):
        print(f"  ground {gid} ({i + 1}/{len(ids)})", flush=True)
        url = f"https://www.njsbcl.com/NJSBCL/viewGround.do?groundId={gid}&clubId=2690"
        id_to_addr[gid] = parse_ground_address(fetch(url))
        time.sleep(0.15)

    entries = [
        {
            "team": team,
            "groundName": gname,
            "address": id_to_addr.get(gid or "", ""),
        }
        for team, gid, gname in parsed
        if gid and gname
    ]

    body = json.dumps(entries, indent=2)
    ts = f"""/**
 * AUTO-GENERATED by scripts/scrape_njsbcl_grounds.py — do not edit.
 * Source: {TEAMS_URL}
 * Generated at: {time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
 */

export type TeamHomeGroundEntry = {{
  team: string;
  groundName: string;
  address: string;
}};

export const TEAM_HOME_GROUND_ENTRIES: TeamHomeGroundEntry[] = {body};
"""
    OUT.write_text(ts, encoding="utf-8")
    print(f"Wrote {len(entries)} entries → {OUT}", flush=True)


if __name__ == "__main__":
    main()
